### ISSUE TITLE
Chart operations aren't working

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#464] opened 2017-10-20 12:58 UTC
- Some parameters aren't displayed in the execution sidebar
- Suggestion attributes aren't working

@michelboaventura @mgonc 

![chart_error](https://user-images.githubusercontent.com/6419508/31821910-76d1780c-b585-11e7-929d-694c87d5e6a8.png)

**Comment by michelboaventura** [comment] 2017-10-25 12:51
@ojvictor, I couldn't reproduce this. It is happening all the time?

**Comment by mgonc** [comment] 2017-10-25 17:36
fixed in #467

**Closed** 2017-10-26 16:51 UTC
Labels: bug
